############################
#  Anon Chihaya Bot 配置   #
# 对需要启动的机器人进行配置 #
############################
# 配置机器人的主人账号
# 将你自己的账号填入这里
host_id: ""

# 以下内容为针对 Satori 协议进行的配置
# Anon Chihaya Bot 默认选用该协议启动
Satori:
  # 支持单协议的多实例运行，单个实例单独进行设定，前后无顺序关系
  # WARNING: 请不要对多个实例进行相同的配置，尽管这并不会影响实际的运行
  - version: 1 # Satori 协议版本，目前只有 1
    # WebSocket 服务连接所需配置
    WebSocket:
      ip: "127.0.0.1" # 进行连接的 WebSocket 所在服务器 IP，本地启动则填入 127.0.0.1
      port: 5140 # 进行连接的端口
      path: "/" # 进行连接的路径，若不需要则可以置空
      token: "" # 进行鉴权需要的 token
      heartbeat_interval: 5 # 心跳时间间隔，单位为秒，设置时间 < 10s
    # 框架自主进行 HTTP POST 推送所需配置 (可选配置)
    WebHook_Client:
      ip: "127.0.0.1" # HTTP 监听服务器地址 IP，本地监听则填入 127.0.0.1
      port: 8800 # HTTP 监听服务器端口
      path: "/" # HTTP 监听服务器路径，若无路径则默认为 "/"
    # 本地 HTTP WebHook 服务监听所需配置 (可选配置)
    WebHook_Server:
      ip: "127.0.0.1" # Satori 协议运行所在地址 IP，本地运行则填入 127.0.0.1
      port: 5140 # 进行连接的端口
      path: "/" # 进行连接的路径，若不需要则可以置空
      token: "" # 进行鉴权需要的 token

  #- version: 1
  #  WebSocket:
  #    ip: "127.0.0.1"
  #    port: 5500
  #    path: ""
  #    token: ""
  #    heartbeat_interval: 5
  #  Webhook_Client:
  #    ip: "127.0.0.1"
  #    port: 8800
  #    path: "/"
  #  Webhook_Server:
  #    ip: ""
  #    port: 8800
  #    path: "/"
  #    token: ""
